name: nataerin
favicon: null
layout_spectrum: 0.42626358289271593
typography_spectrum: 0.1576190493069589
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09043168346397579
  lightness: 0.35410811728797853
  saturation: 0.4115423928014934
  rhythmicContrast: 0.9780392409302294
purpose: []
